- hosts: terraform-ansible
  tasks:
  - name: Installing python3 and venv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: Installing dependencies with pip
    pip:
      virtualenv: /home/ubuntu/application/venv
      name:
        - django
        - djangorestframework
  - name: Initializing project
    shell: '. /home/ubuntu/application/venv/bin/activate; django-admin startproject setup /home/ubuntu/application/'
    #shell: 'ls'
  - name: Changing settings hosts
    lineinfile:
      path: /home/application/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes