- hosts: terraform-ansible
  tasks:
  - name: Creating file
    copy: 
      dest: /home/ubuntu/index.html
      content: <h1>Done with Terraform and Ansible</h1>
  - name: Creating server
    shell: "nohup busyhop httpd -f -p 8080 &"