- hosts: terraform-ansible
  tasks:
  - name: Installing python3 and venv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: Installing dependencies with pip
    pip:
      virtualenv: /home/ubuntu/application/venv
      name:
        - django
        - djangorestframework